version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "No dependencies to install."

  build:
    commands:
      - echo "Zipping LF1..."
      - zip -rj LF1.zip LambdaFunction/LF1/* 
      - echo "Checking if LF1.zip exists:"
      - ls -la

artifacts:
  files:
    - LF1.zip
  discard-paths: yes
