version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r LambdaFunction/LF1/requirements.txt -t LambdaFunction/LF1/
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cd LambdaFunction/LF1 && zip -r ../../LF1.zip . && cd ../../
      - echo "Build completed. Verifying package contents..."
      - ls -la LF1.zip
      - cp appspec.yml ./  # Copy appspec.yml into the build output directory
artifacts:
  files:
    - LF1.zip
    - appspec.yml  # Include the AppSpec file in the artifact
  discard-paths: yes
