version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Dependencies are already installed. Skipping installation."
  build:
    commands:
      - echo "Zipping LF1..."
      - cd LambdaFunction/LF1 && zip -r ../../LF1.zip . && cd ../../
      - echo "Zipping LF2..."
      - cd LambdaFunction/LF2 && zip -r ../../LF2.zip . && cd ../../
      - echo "Checking if LF1.zip and LF2.zip exist:"
      - ls -la

artifacts:
  files:
    - LF1.zip
    - LF2.zip
  base-directory: .
